### ISSUE TITLE
Adding to mod description page

### ISSUE THREAD

**Issue by Anders142536** [nickolasbradham/Factorio-Screenshot-Stitcher#1]
Hey,

I saw you forking my image-stitcher.

The way I understood your code from dry reading you wrapped a small ui around the program and removed the multithreading support?

If you are confident in your program and are okay with it I would add your github repo to the list of image stitchers i have in the mod description. Same as I did with the alternative provided by [NathanaelMangold](https://github.com/NathanaelMangold). Your version would also be the only one with a ui, which a lot of non-techie people might appreciate

**Comment by nickolasbradham** [comment]
I originally forked your image stitcher, but I ended up not getting the dependencies to work, so I started from scratch. I think you might have looked at my super early version. The latest version DOES have basic multithreading and a slightly more descriptive UI. I might make a few more tweaks and give a few options in future, but the core program is done.

I would be honored to have my project on your description. Thank you.

**Comment by Anders142536** [comment]
I see, you added multithreading support.

I think basing the number of threads on the number of available cores might cause out of memory exceptions in some setups.

I will add you to my list of stitchers tomorrow or so.

Thx for doing this.

**Comment by nickolasbradham** [comment]
I added a catch for OutOfMemoryErrors that just tacks the failed stitches back into the queue for the other threads. Worst case scenario all threads crash and the program just exits, but as long as one thread remains, all images will be stitched. I'm not proud of that solution, but it works as far as I've tested. I'll update the Readme to be more useful as well.
